version: '3'
services:
  python3:
    restart: always
    build: .
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/src
    ports:
      - 9000:9000
    environment:
      - PORT=9000